-- MySQL Script generated by MySQL Workbench
-- Fri Oct 20 10:00:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema u322424575_Adminabq
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `u322424575_Adminabq` ;

-- -----------------------------------------------------
-- Schema u322424575_Adminabq
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u322424575_Adminabq` DEFAULT CHARACTER SET utf8 ;
USE `u322424575_Adminabq` ;

-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`tipo_documentacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`tipo_documentacion` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`tipo_documentacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` LONGTEXT NOT NULL,
  `descripcion` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`usuario` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` LONGTEXT NOT NULL,
  `email` LONGTEXT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `fecha_nacimeinto` DATE NOT NULL,
  `password` LONGTEXT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `telefono` LONGTEXT NOT NULL,
  `numero_documento` LONGTEXT NULL,
  `tipo_documentacion_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_tipo_documentacion1_idx` (`tipo_documentacion_id` ASC),
  CONSTRAINT `fk_usuario_tipo_documentacion1`
    FOREIGN KEY (`tipo_documentacion_id`)
    REFERENCES `u322424575_Adminabq`.`tipo_documentacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`rol` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`usuario_has_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`usuario_has_rol` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`usuario_has_rol` (
  `usuario_id` INT NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `rol_id`),
  INDEX `fk_usuario_has_rol_rol1_idx` (`rol_id` ASC),
  INDEX `fk_usuario_has_rol_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuario_has_rol_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `u322424575_Adminabq`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_rol_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `u322424575_Adminabq`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`tipo_propiedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`tipo_propiedad` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`tipo_propiedad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` LONGTEXT NOT NULL,
  `descripcion` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`cojunto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`cojunto` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`cojunto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` LONGTEXT NOT NULL,
  `direccion` LONGTEXT NOT NULL,
  `ciudad` LONGTEXT NOT NULL,
  `departamento` LONGTEXT NOT NULL,
  `codigo_postal` VARCHAR(7) NOT NULL,
  `codigo` LONGTEXT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `fecha_creacion` DATETIME NOT NULL,
  `correo` LONGTEXT NOT NULL,
  `password` LONGTEXT NOT NULL,
  `telefono` LONGTEXT NOT NULL,
  `nombre_propietario` LONGTEXT NULL,
  `numero_documento` LONGTEXT NULL,
  `tipo_propiedad_id` INT NOT NULL,
  `usuario_id` INT NULL,
  `tipo_documentacion_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_propiedad_tipo_propiedad1_idx` (`tipo_propiedad_id` ASC),
  INDEX `fk_cojunto_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_cojunto_tipo_documentacion1_idx` (`tipo_documentacion_id` ASC),
  CONSTRAINT `fk_propiedad_tipo_propiedad1`
    FOREIGN KEY (`tipo_propiedad_id`)
    REFERENCES `u322424575_Adminabq`.`tipo_propiedad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cojunto_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `u322424575_Adminabq`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cojunto_tipo_documentacion1`
    FOREIGN KEY (`tipo_documentacion_id`)
    REFERENCES `u322424575_Adminabq`.`tipo_documentacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`torre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`torre` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`torre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` LONGTEXT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `cojunto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_torre_cojunto1_idx` (`cojunto_id` ASC),
  CONSTRAINT `fk_torre_cojunto1`
    FOREIGN KEY (`cojunto_id`)
    REFERENCES `u322424575_Adminabq`.`cojunto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`propiedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`propiedad` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`propiedad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` LONGTEXT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `cojunto_id` INT NOT NULL,
  `torre_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_propiedad_cojunto1_idx` (`cojunto_id` ASC),
  INDEX `fk_propiedad_torre1_idx` (`torre_id` ASC),
  CONSTRAINT `fk_propiedad_cojunto1`
    FOREIGN KEY (`cojunto_id`)
    REFERENCES `u322424575_Adminabq`.`cojunto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_propiedad_torre1`
    FOREIGN KEY (`torre_id`)
    REFERENCES `u322424575_Adminabq`.`torre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`usuario_has_propiedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`usuario_has_propiedad` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`usuario_has_propiedad` (
  `usuario_id` INT NOT NULL,
  `propiedad_id` INT NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `propiedad_id`),
  INDEX `fk_usuario_has_propiedad_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_usuario_has_propiedad_propiedad1_idx` (`propiedad_id` ASC),
  CONSTRAINT `fk_usuario_has_propiedad_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `u322424575_Adminabq`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_propiedad_propiedad1`
    FOREIGN KEY (`propiedad_id`)
    REFERENCES `u322424575_Adminabq`.`propiedad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`tipo_revision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`tipo_revision` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`tipo_revision` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` LONGTEXT NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `cojunto_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tipo_revision_cojunto1_idx` (`cojunto_id` ASC),
  CONSTRAINT `fk_tipo_revision_cojunto1`
    FOREIGN KEY (`cojunto_id`)
    REFERENCES `u322424575_Adminabq`.`cojunto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`revision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`revision` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`revision` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` LONGTEXT NOT NULL,
  `ruta` LONGTEXT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `tipo_revision_id` INT NOT NULL,
  `propiedad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_revision_tipo_revision1_idx` (`tipo_revision_id` ASC),
  INDEX `fk_revision_propiedad1_idx` (`propiedad_id` ASC),
  CONSTRAINT `fk_revision_tipo_revision1`
    FOREIGN KEY (`tipo_revision_id`)
    REFERENCES `u322424575_Adminabq`.`tipo_revision` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_revision_propiedad1`
    FOREIGN KEY (`propiedad_id`)
    REFERENCES `u322424575_Adminabq`.`propiedad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`notificacion` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`notificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mensaje` LONGTEXT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `visto` INT NOT NULL DEFAULT 0,
  `user` INT NULL,
  `conjunto` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`tipo_cuenta_bancaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`tipo_cuenta_bancaria` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`tipo_cuenta_bancaria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` LONGTEXT NOT NULL,
  `code` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`cuentas_bancarias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`cuentas_bancarias` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`cuentas_bancarias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` LONGTEXT NOT NULL,
  `cuenta` LONGTEXT NOT NULL,
  `code` INT NOT NULL,
  `cojunto_id` INT NULL,
  `usuario_id` INT NULL,
  `tipo_cuenta_bancaria_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cuentas_bancarias_cojunto1_idx` (`cojunto_id` ASC),
  INDEX `fk_cuentas_bancarias_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_cuentas_bancarias_tipo_cuenta_bancaria1_idx` (`tipo_cuenta_bancaria_id` ASC),
  CONSTRAINT `fk_cuentas_bancarias_cojunto1`
    FOREIGN KEY (`cojunto_id`)
    REFERENCES `u322424575_Adminabq`.`cojunto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuentas_bancarias_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `u322424575_Adminabq`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuentas_bancarias_tipo_cuenta_bancaria1`
    FOREIGN KEY (`tipo_cuenta_bancaria_id`)
    REFERENCES `u322424575_Adminabq`.`tipo_cuenta_bancaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`muro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`muro` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`muro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` LONGTEXT NOT NULL,
  `nombre_user` LONGTEXT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `cojunto_id` INT NOT NULL,
  `user` INT NULL,
  `cojunto` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_muro_cojunto1_idx` (`cojunto_id` ASC),
  CONSTRAINT `fk_muro_cojunto1`
    FOREIGN KEY (`cojunto_id`)
    REFERENCES `u322424575_Adminabq`.`cojunto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`comentario` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`comentario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comentario` LONGTEXT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `nombre_user` LONGTEXT NOT NULL,
  `muro_id` INT NOT NULL,
  `user` INT NULL,
  `cojunto` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comentario_muro1_idx` (`muro_id` ASC),
  CONSTRAINT `fk_comentario_muro1`
    FOREIGN KEY (`muro_id`)
    REFERENCES `u322424575_Adminabq`.`muro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`pagos` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`pagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pago` INT NOT NULL,
  `status` INT NOT NULL,
  `fecha` DATE NULL,
  `current_create` DATETIME NOT NULL,
  `propiedad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pagos_propiedad1_idx` (`propiedad_id` ASC),
  CONSTRAINT `fk_pagos_propiedad1`
    FOREIGN KEY (`propiedad_id`)
    REFERENCES `u322424575_Adminabq`.`propiedad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u322424575_Adminabq`.`transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u322424575_Adminabq`.`transaccion` ;

CREATE TABLE IF NOT EXISTS `u322424575_Adminabq`.`transaccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `precio` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `fecha_pago` DATETIME NULL,
  `statud` INT NOT NULL,
  `idPayout` LONGTEXT NULL,
  `usuario_has_propiedad_usuario_id` INT NOT NULL,
  `usuario_has_propiedad_propiedad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transaccion_usuario_has_propiedad1_idx` (`usuario_has_propiedad_usuario_id` ASC, `usuario_has_propiedad_propiedad_id` ASC),
  CONSTRAINT `fk_transaccion_usuario_has_propiedad1`
    FOREIGN KEY (`usuario_has_propiedad_usuario_id` , `usuario_has_propiedad_propiedad_id`)
    REFERENCES `u322424575_Adminabq`.`usuario_has_propiedad` (`usuario_id` , `propiedad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `u322424575_Adminabq`.`tipo_documentacion`
-- -----------------------------------------------------
START TRANSACTION;
USE `u322424575_Adminabq`;
INSERT INTO `u322424575_Adminabq`.`tipo_documentacion` (`id`, `nombre`, `descripcion`) VALUES (11, 'Registro civil', NULL);
INSERT INTO `u322424575_Adminabq`.`tipo_documentacion` (`id`, `nombre`, `descripcion`) VALUES (12, 'Tarjeta de identidad', NULL);
INSERT INTO `u322424575_Adminabq`.`tipo_documentacion` (`id`, `nombre`, `descripcion`) VALUES (13, 'Cédula de ciudadanía', NULL);
INSERT INTO `u322424575_Adminabq`.`tipo_documentacion` (`id`, `nombre`, `descripcion`) VALUES (21, 'Tarjeta de extranjeria', NULL);
INSERT INTO `u322424575_Adminabq`.`tipo_documentacion` (`id`, `nombre`, `descripcion`) VALUES (22, 'Cédula de extranjeria', NULL);
INSERT INTO `u322424575_Adminabq`.`tipo_documentacion` (`id`, `nombre`, `descripcion`) VALUES (31, 'NIT', NULL);
INSERT INTO `u322424575_Adminabq`.`tipo_documentacion` (`id`, `nombre`, `descripcion`) VALUES (41, 'Pasaporte', NULL);
INSERT INTO `u322424575_Adminabq`.`tipo_documentacion` (`id`, `nombre`, `descripcion`) VALUES (42, 'Documento de identificación extranjeria', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `u322424575_Adminabq`.`tipo_cuenta_bancaria`
-- -----------------------------------------------------
START TRANSACTION;
USE `u322424575_Adminabq`;
INSERT INTO `u322424575_Adminabq`.`tipo_cuenta_bancaria` (`id`, `nombre`, `code`) VALUES (1, 'Ahorro', 'SAVINGS');
INSERT INTO `u322424575_Adminabq`.`tipo_cuenta_bancaria` (`id`, `nombre`, `code`) VALUES (2, 'Corriente', 'CHECKING');
INSERT INTO `u322424575_Adminabq`.`tipo_cuenta_bancaria` (`id`, `nombre`, `code`) VALUES (3, 'Deposito electronico', 'ELECTRONIC_DEPOSIT');

COMMIT;

