-- MySQL Script generated by MySQL Workbench
-- Thu May 12 21:48:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema admina
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `admina` ;

-- -----------------------------------------------------
-- Schema admina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `admina` DEFAULT CHARACTER SET utf8 ;
USE `admina` ;

-- -----------------------------------------------------
-- Table `admina`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admina`.`usuario` ;

CREATE TABLE IF NOT EXISTS `admina`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` LONGTEXT NOT NULL,
  `email` LONGTEXT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `fecha_nacimeinto` DATE NOT NULL,
  `password` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admina`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admina`.`rol` ;

CREATE TABLE IF NOT EXISTS `admina`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admina`.`usuario_has_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admina`.`usuario_has_rol` ;

CREATE TABLE IF NOT EXISTS `admina`.`usuario_has_rol` (
  `usuario_id` INT NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `rol_id`),
  INDEX `fk_usuario_has_rol_rol1_idx` (`rol_id` ASC),
  INDEX `fk_usuario_has_rol_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuario_has_rol_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `admina`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_rol_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `admina`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
